channels:
  - name: "강민의 금일봉"
    invite_link: "https://t.me/goldilbong"
    category: "stock"

  - name: "베이지컬리"
    invite_link: "https://t.me/basixally"
    category: "crypto"

  - name: "TEAM GOBO"
    invite_link: "https://t.me/Goboclub"
    category: "crypto"

  - name: "실전매매전략"
    invite_link: "https://t.me/stockgrandmaster"
    category: "stock"

  - name: "가치투자전략"
    invite_link: "https://t.me/corevalue"
    category: "stock"

  - name: "하이불스"
    invite_link: "https://t.me/hibulls"
    category: "stock"

  - name: "급등일보"
    invite_link: "https://t.me/FastStockNews"
    category: "stock"

  - name: "미국급등일보"
    invite_link: "https://t.me/FastStockNewsUSA"
    category: "stock"

  - name: "레드존"
    invite_link: "https://t.me/REDZONEMONEY"
    category: "stock"

  - name: "TNB"
    invite_link: "https://t.me/TNBfolio"
    category: "stock"

  - name: "신한투자증권"
    invite_link: "https://t.me/chel3337"
    category: "stock"

  - name: "드리고"
    invite_link: "https://t.me/dreago_news_ch"
    category: "stock"

  - name: "실시간"
    invite_link: "https://t.me/realtime_stock_news"
    category: "stock"

  - name: "여의도랩"
    invite_link: "https://t.me/Yeouido_Lab"
    category: "stock"

  - name: "미국인사이더"
    invite_link: "https://t.me/insidertracking"
    category: "stock"

  - name: "머니서퍼"
    invite_link: "https://t.me/moneythemestock"
    category: "stock"

  - name: "rafiki"
    invite_link: "https://t.me/rafikiresearch"
    category: "stock"

  - name: "여의도스토리"
    invite_link: "https://t.me/YeouidoStory2"
    category: "stock"

  - name: "주식클라쓰"
    invite_link: "https://t.me/sharpha"
    category: "stock"

  - name: "해외주식 루틴"
    invite_link: "https://t.me/c/1579665908"
    category: "stock"

  - name: "기술적분석"
    invite_link: "https://t.me/hermitcrab41"
    category: "stock"

  - name: "피카츄"
    invite_link: "https://t.me/pikachu_aje"
    category: "stock"

  - name: "상장기업"
    invite_link: "https://t.me/cyber_rangers"
    category: "stock"

  - name: "동물원"
    invite_link: "https://t.me/stockinvcowcow"
    category: "stock"

  - name: "이지스"
    invite_link: "https://t.me/jeilstock"
    category: "stock"

  - name: "키움증권"
    invite_link: "https://t.me/kwusa"
    category: "stock"

  - name: "씽크풀"
    invite_link: "https://t.me/rassiro_channel"
    category: "stock"

  - name: "뉴스귀신"
    invite_link: "https://t.me/ghoststock"
    category: "stock"

  - name: "대세산업"
    invite_link: "https://t.me/major_industry"
    category: "stock"

  - name: "바바리안"
    invite_link: "https://t.me/Barbarianglobal"
    category: "stock"

  - name: "AI 리서치"
    invite_link: "https://t.me/aicorporateanalysisdeepdive"
    category: "stock"


  - name: "웨돔"
    invite_link: "https://t.me/wedomnbro"
    category: "crypto"
