channels:
  - name: "강민의 금일봉"
    invite_link: "https://t.me/goldilbong"
    category: "stock"

  - name: "베이지컬리"
    invite_link: "https://t.me/basixally"
    category: "crypto"

  - name: "TEAM GOBO"
    invite_link: "https://t.me/Goboclub"
    category: "crypto"

  - name: "실전매매전략"
    invite_link: "https://t.me/stockgrandmaster"
    category: "stock"

  - name: "가치투자전략"
    invite_link: "https://t.me/corevalue"
    category: "stock"

